version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
  - package-ecosystem: "bundler"
    directory: "/apps/api"
    schedule: { interval: "weekly" }
