version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kit_builders_dev
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/kit_builders_dev
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      RACK_ENV: development
      SECRET_KEY_BASE: devsecretchangeme
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    volumes:
      - ./apps/api:/app

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    # Process both default and mailers queues so WelcomeEmailWorker runs
    command: ["bundle", "exec", "sidekiq", "-q", "default", "-q", "mailers"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/kit_builders_dev
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      SECRET_KEY_BASE: devsecretchangeme
    depends_on:
      - api
      - redis
    volumes:
      - ./apps/api:/app

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      NODE_OPTIONS: "--openssl-legacy-provider"
      NEXT_PUBLIC_ASSET_BASE: "http://localhost:9000/dev-bucket"
      PNPM_STORE_DIR: "/app/.pnpm-store"
      INTERNAL_API_HOST: "api:4000"
    ports:
      - "3000:3000"
    depends_on:
      - api
    # No bind mount: we rely on image node_modules to keep native binaries present
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

volumes:
  pgdata: {}
  minio_data: {}
